dist: xenial

install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.68.3/hugo_extended_0.68.3_Linux-64bit.deb
  - sudo dpkg -i hugo*.deb

script:
  - GITHUB_TOKEN=$GITHUB_TOKEN hugo

deploy:
  provider: pages
  github_token: $GITHUB_TOKEN
  local_dir: public
  fqdn: staging.paketo.io
  skip_cleanup: true
  verbose: true
  on:
    branch: master
