baseURL = "https://paketo.io/"
title = "Paketo Buildpacks"

pygmentsUseClasses = true
pygmentsCodefences = true

enableRobotsTXT = true

# path name excluded from documentation menu
menu_exclusion = [
    "contribute",
    "docs"
]

[frontmatter]
lastmod = ["lastmod", ":fileModTime", ":default"]

[params.hero]
    headline = "Paketo Buildpacks"
    subheadline = "Your app, in your favorite language, ready to run in the cloud"

    cta_text = "GET STARTED"
    cta_link = "/docs/"

    [[params.hero.logos]]
        [[params.hero.logos.item]]
            img = "java-logo.svg"
            alt = "java logo"
            docs= "java"
            css_class = "logo-java"

        [[params.hero.logos.item]]
            img = "GraalVM-logo.svg"
            alt = "GraalVM logo"
            docs= "java-native-image"
            css_class = "logo-graalvm"

        [[params.hero.logos.item]]
            img = "go-logo.svg"
            alt = "go logo"
            docs= "go"
            css_class = "logo-go"

        [[params.hero.logos.item]]
            img = "net-core-logo.svg"
            alt = ".net core logo"
            docs= "dotnet-core"
            css_class = "logo-dotnet-core"

        [[params.hero.logos.item]]
            img = "nginx-logo.svg"
            alt = "nginx logo"
            docs= "nginx"
            css_class = "logo-nginx"

        [[params.hero.logos.item]]
            img = "nodejs-logo.svg"
            alt = "nodejs logo"
            docs= "nodejs"
            css_class = "logo-nodejs"

        [[params.hero.logos.item]]
            img = "php-logo.svg"
            alt = "php logo"
            docs= "php"
            css_class = "logo-php"

        [[params.hero.logos.item]]
            img = "httpd-logo.svg"
            alt = "httpd logo"
            docs= "httpd"
            css_class = "logo-httpd"

        [[params.hero.logos.item]]
            img = "ruby-logo.svg"
            alt = "ruby logo"
            docs= "ruby"
            css_class = "logo-ruby"

[params.what_are_buildpacks]
  headline = "What are Buildpacks?"
  description = "Buildpacks transform your application source code to images that can run on any cloud. Paketo Buildpacks provide language runtime support for applications. They leverage the Cloud Native Buildpacks framework to make image builds easy, performant, and secure."
  cta_text = "More about the Cloud Native Buildpacks project"
  cta_link = "https://buildpacks.io"


[params.why_paketo]
    headline = "Why Paketo Buildpacks?"
    copy = ""

  [[params.why_paketo.item]]
    title = "Secure"
    description = "The Paketo project ensures that upstream languages, runtimes, and frameworks are continuously patched in response to vulnerabilities and updates."
    image = "images/secure.svg"

  [[params.why_paketo.item]]
    title = "Standardized"
    description = "Paketo Buildpacks implement the Cloud Native Buildpacks specification, an emerging standard for building app container images. You can use Paketo Buildpacks with tools such as the CNB pack CLI, kpack, Tekton, and Skaffold, in addition to a number of cloud platforms."
    image = "images/standardized.svg"
    reverse_class = "reverse"

  [[params.why_paketo.item]]
    title = "Community-Driven"
    description = "The Paketo Buildpacks project lives within the Cloud Foundry Foundation and is dedicated to maintaining a vendor-neutral governance process."
    image = "images/community.svg"

[params.get_started]
  [[params.get_started.item]]
    icon = "paketo-documentation.svg"
    text = "Get Started"
    link = "/docs/"

[params.docs_menu]
  title = "PAKETO DOCS"


[module]
  [[module.imports]]
    path = "github.com/paketo-buildpacks/dotnet-core/docs"

    [[module.imports.mounts]]
      source = "content/dotnet-core.md"
      target = "content/docs/buildpacks/language-family-buildpacks/dotnet-core.md"
