baseURL = "https://www.paketo.io/"
title = "Paketo Buildpacks: Framework and runtime support for apps"


[params.hero]
  headline = "Paketo Buildpacks: Framework and runtime support for apps"
  subhead = "Paketo is a collection of Cloud Native Buildpack compliant buildpacks for the most common enterprise development languages and frameworks."
  cta_text = "Paketo Docs"
  cta_link = "https://www.paketo.io"

[params.why_paketo]
    headline = "Why Paketo Buildpacks?"
    copy = "Paketo Buildpacks are for developers and operators that build and deploy applications to cloud native platforms and build systems that support the Cloud Native Buildpack specification, working within any Cloud Native Platform (Kubernetes, Cloud Foundry, etc.)."

  [[params.why_paketo.item]]
    title = "Quality"
    description = "The Paketo project team has been authoring buildpacks for over five years, and has incorporated feedback from hundreds of thousands of developers."
    
  [[params.why_paketo.item]]
    title = "Security"
    description = "The Paketo project team works hard to ensure swift roll-out of security patches in response to the vulnerabilities in upstream language runtimes and frameworks."

  [[params.why_paketo.item]]
    title = "Continued Innovation"
    description = "The Paketo project team incorporates feedback from developers around the world in order to keep the buildpack collection up to date with best industry practices."

  [[params.why_paketo.item]]
    title = "Industry standard"
    description = "Paketo buildpacks are compliant with the latest version of the CNB specification."


[params.faq]
  headline = "FAQ"

  [[params.faq.item]]
    q = "How are Paketo Buildpacks different from Cloud Foundry Buildpacks?"
    a = "Cloud Foundry Buildpacks have been restructured so they can be used in any cloud native environment. As such, they are now called Paketo Buildpacks. Paketo Buildpacks are CNB compliant -- the legacy Cloud Foundry Buildpacks are not."

  [[params.faq.item]]
    q = "How are Paketo Buildpacks different from the Cloud Native Buildpack project?"
    a = "Cloud Native Buildpacks (CNB) is a specification and set of tools for how buildpacks are structured. Paketo buildpacks implement that specification into a collection of usable buildpacks. Learn more at <a class='cta' href='buildpacks.io'>buildpacks.io</a>."

  [[params.faq.item]]
    q = "What if I’m using Cloud Foundry Buildpacks? How do I make the change to Paketo Buildpacks?"
    a = "The Cloud Foundry Buildpacks team is already working on Paketo Buildpacks and will ensure a smooth transition for developers using Cloud Foundry Buildpacks."

  [[params.faq.item]]
    q = "What languages and frameworks can I use with Paketo Buildpacks?"
    a = "At launch, Paketo Buildpacks will officially support the Java and NodeJS Paketo Buildpacks as well as tools/libraries that allow you to build and test your own Paketo Buildpacks. The team is also actively developing .Net, PHP, Golang, and Python Paketo Buildpacks."

  [[params.faq.item]]
    q = "How do I contribute to Paketo Buildpacks?"
    a = "Join the Paketo Buildpacks working group meetings to introduce yourself and hear about what’s in flight."
  
[params.get_started]
  headline = "Get Started with Paketo Buildpacks"

  [[params.get_started.item]]
    icon = "paketo-documentation.svg"
    text = "Documentation"
    link = "#"

  [[params.get_started.item]]
    icon = "paketo-tutorial.svg"
    text = "Tutorial"
    link = "#"

  [[params.get_started.item]]
    icon = "paketo-slack.svg"
    text = "Paketo Slack"
    link = "https://www.paketo.io"

  [[params.get_started.item]]
    icon = "paketo-blog.svg"
    text = "Paketo Blog"
    link = "#"