name: Check Site Links

on:
  schedule:
  - cron: '0 5 * * *'  # Every day at 0500

jobs:
  check-site-links:
    name: Check For Broken Links
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.5
      with:
        submodules: false
    - name: Crawl live site for broken links
      run: scripts/check-links.sh --live
